---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base
    - env_vars/dev
    - group_vars/dbservers
    - group_vars/webservers

  roles:
    - base
    - db
    - web