---

- name: Provision a {{ application_name }} web server
  hosts: webservers
  become: yes
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3  # remove this var if using an Ubuntu version older than 16.04
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - certbot
    - rabbitmq
    - web
    - celery
    - nginx
