---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Install security updates
  apt: default_release={{ ansible_distribution_release }}-security
       update_cache={{ update_apt_cache }}
       upgrade=dist
  tags: packages
        skip_ansible_lint

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - ipython
    - supervisor
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages
        skip_ansible_lint

- name: Add the PostgreSQL repository key to the apt trusted keys
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           state=present

- name: Add the PostgreSQL repository to the apt sources list
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Add repository for Python 3.5 to the sources list
  apt_repository: repo='ppa:fkrull/deadsnakes'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Python 3.5 and related packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - python3.5
    - python3.5-dev
    - python3-pip
    - ipython3
  tags: packages
